name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # uv doc: https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project's environment
        run: |
          uv sync --all-extras --dev
      - name: Run ruff
        run: |
          uvx ruff check
          uvx ruff format --check
      - name: Install the project
        run: |
          uv pip install .
      - name: Run mypy
        run: |
          uv run mypy
      - name: Run pytest with coverage
        run: |
          uv run pytest --cov-report=xml
      # Setup codecov later
